.TH "src/hardware.c" 3 "Mon Oct 26 2020" "Version v1.1" "Pygmy Possum" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hardware.c
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'hardware\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHardware_ConfigureOscillator\fP ()"
.br
.ti -1c
.RI "void \fBHardware_initIO\fP ()"
.br
.ti -1c
.RI "void \fBHardware_initUART\fP ()"
.br
.ti -1c
.RI "void \fBHardware_UARTsendByte\fP (uint8_t Tx)"
.br
.ti -1c
.RI "void \fBHardware_UARTsendString\fP (char Tx[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Hardware_ConfigureOscillator ()"

.SS "void Hardware_initIO ()"

.SS "void Hardware_initUART ()"

.SS "void Hardware_UARTsendByte (uint8_t Tx)"

.SS "void Hardware_UARTsendString (char Tx[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pygmy Possum from the source code\&.
