.TH "src/main.c" 3 "Mon Oct 26 2020" "Version v1.1" "Pygmy Possum" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'configbits\&.h'\fP
.br
\fC#include <xc\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'hardware\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'pygmy\&.h'\fP
.br
\fC#include 'eusart\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSB_POWERED\fP   true"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenuRun\fP (void)"
.br
.ti -1c
.RI "void \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USB_POWERED   true"

.SH "Function Documentation"
.PP 
.SS "void main (void)"

.SS "void menuRun (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pygmy Possum from the source code\&.
